PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_resets_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2026_05_21_000001_create_profiles_table',1);
INSERT INTO migrations VALUES(6,'2026_05_21_000002_create_skills_table',1);
INSERT INTO migrations VALUES(7,'2026_05_21_000004_create_experiences_table',1);
INSERT INTO migrations VALUES(8,'2026_05_21_000005_create_contact_messages_table',1);
INSERT INTO migrations VALUES(9,'2026_05_21_000006_create_hobbies_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Wildan Admin','admin@wildan.test',NULL,'$2y$10$p/MeZDYPdgug5EjUPufsueDom.M/Bzpy./crcZkW8ELndguqDC1h6',NULL,'2026-05-21 01:57:48','2026-05-21 01:57:48');
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer not null primary key autoincrement, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime default CURRENT_TIMESTAMP not null);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer not null primary key autoincrement, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profiles" ("id" integer not null primary key autoincrement, "name" varchar not null, "headline" varchar not null, "bio" text, "email" varchar, "phone" varchar, "location" varchar, "avatar_url" varchar, "social_links" text, "created_at" datetime, "updated_at" datetime);
INSERT INTO profiles VALUES(1,'Wildan','Full Stack Developer','Saya membangun web app dengan React dan Laravel, sambil terus belajar dari pengalaman sekolah, hobi, dan latihan coding sehari-hari.','hello@wildan.test','+62 812 0000 0000','Jakarta, Indonesia','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80','{"github":"https:\/\/github.com\/wildan","linkedin":"https:\/\/linkedin.com\/in\/wildan","instagram":"https:\/\/instagram.com\/wildan"}','2026-05-21 01:57:48','2026-05-21 01:57:48');
CREATE TABLE IF NOT EXISTS "skills" ("id" integer not null primary key autoincrement, "name" varchar not null, "category" varchar not null, "level" varchar, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO skills VALUES(1,'ReactJS','Frontend','Advanced',1,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO skills VALUES(2,'Laravel','Backend','Advanced',2,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO skills VALUES(3,'REST API','Backend','Advanced',3,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO skills VALUES(4,'UI Implementation','Frontend','Intermediate',4,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO skills VALUES(5,'Database Design','Backend','Intermediate',5,'2026-05-21 01:57:48','2026-05-21 01:57:48');
CREATE TABLE IF NOT EXISTS "experiences" ("id" integer not null primary key autoincrement, "title" varchar not null, "organization" varchar not null, "location" varchar, "start_date" varchar not null, "end_date" varchar, "description" text, "type" varchar not null default 'work', "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO experiences VALUES(1,'SD','Sekolah Dasar','Indonesia','2014','2020','Membangun dasar belajar, disiplin, membaca, menulis, dan rasa ingin tahu.','study',1,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO experiences VALUES(2,'SMP','Sekolah Menengah Pertama','Indonesia','2020','2023','Mulai mengenal kerja kelompok, presentasi, teknologi, dan minat ke dunia komputer.','study',2,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO experiences VALUES(3,'SMK','Sekolah Menengah Kejuruan','Indonesia','2023','Present','Fokus pada pembelajaran kejuruan, dasar pemrograman, web development, dan kesiapan karir.','study',3,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO experiences VALUES(4,'Karir Awal','Belajar & Praktik Mandiri','Remote','2024','Present','Mengerjakan latihan web, portfolio, dan eksplorasi React serta Laravel untuk bekal kerja.','career',4,'2026-05-21 01:57:48','2026-05-21 01:57:48');
CREATE TABLE IF NOT EXISTS "contact_messages" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "subject" varchar not null, "message" text not null, "is_read" tinyint(1) not null default '0', "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "hobbies" ("id" integer not null primary key autoincrement, "name" varchar not null, "description" text, "sort_order" integer not null default '0', "created_at" datetime, "updated_at" datetime);
INSERT INTO hobbies VALUES(1,'Coding','Mencoba fitur web baru, membuat eksperimen kecil, dan belajar framework modern.',1,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO hobbies VALUES(2,'Futsal','Melatih kerja sama, komunikasi, dan disiplin lewat permainan tim.',2,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO hobbies VALUES(3,'Desain UI','Mencari referensi tampilan gelap, layout dashboard, dan palet warna yang nyaman.',3,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO hobbies VALUES(4,'Musik','Menemani belajar dan membantu menjaga fokus saat mengerjakan tugas.',4,'2026-05-21 01:57:48','2026-05-21 01:57:48');
INSERT INTO sqlite_sequence VALUES('migrations',9);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('profiles',1);
INSERT INTO sqlite_sequence VALUES('skills',5);
INSERT INTO sqlite_sequence VALUES('hobbies',4);
INSERT INTO sqlite_sequence VALUES('experiences',4);
INSERT INTO sqlite_sequence VALUES('personal_access_tokens',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
COMMIT;
